// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: user.proto

package userpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserServiceRpcClient is the client API for UserServiceRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceRpcClient interface {
	Create(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error)
}

type userServiceRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceRpcClient(cc grpc.ClientConnInterface) UserServiceRpcClient {
	return &userServiceRpcClient{cc}
}

func (c *userServiceRpcClient) Create(ctx context.Context, in *UserRequest, opts ...grpc.CallOption) (*UserResponse, error) {
	out := new(UserResponse)
	err := c.cc.Invoke(ctx, "/user_rpc.UserServiceRpc/create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceRpcServer is the server API for UserServiceRpc service.
// All implementations must embed UnimplementedUserServiceRpcServer
// for forward compatibility
type UserServiceRpcServer interface {
	Create(context.Context, *UserRequest) (*UserResponse, error)
	mustEmbedUnimplementedUserServiceRpcServer()
}

// UnimplementedUserServiceRpcServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceRpcServer struct {
}

func (UnimplementedUserServiceRpcServer) Create(context.Context, *UserRequest) (*UserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedUserServiceRpcServer) mustEmbedUnimplementedUserServiceRpcServer() {}

// UnsafeUserServiceRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceRpcServer will
// result in compilation errors.
type UnsafeUserServiceRpcServer interface {
	mustEmbedUnimplementedUserServiceRpcServer()
}

func RegisterUserServiceRpcServer(s grpc.ServiceRegistrar, srv UserServiceRpcServer) {
	s.RegisterService(&UserServiceRpc_ServiceDesc, srv)
}

func _UserServiceRpc_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceRpcServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user_rpc.UserServiceRpc/create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceRpcServer).Create(ctx, req.(*UserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserServiceRpc_ServiceDesc is the grpc.ServiceDesc for UserServiceRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserServiceRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user_rpc.UserServiceRpc",
	HandlerType: (*UserServiceRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "create",
			Handler:    _UserServiceRpc_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
